services:

  Shared.Logger:
    class: ../../../../Context/Shared/infrastructure/EventBus/InMemory/InMemoryAsyncEventBus
    arguments: []

#  Shared.domain.EventBus:
#    class: ../../../../Context/Shared/infrastructure/EventBus/InMemory/InMemoryAsyncEventBus
#    arguments: []

  Shared.domain.EventBus:
    factory:
      class: ../../../../Context/Plants/infrastructure/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Shared.RabbitMQConnection',
        '@Shared.RabbitMQQueueFormatter',
        '@Shared.RabbitMQConfig'
      ]

  Shared.RabbitMQConfig:
    factory:
      class: ../../../../Context/Plants/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  Shared.RabbitMQConnection:
    class: ../../../../Context/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQConnection
    arguments: ['@Shared.RabbitMQConfig']

  Shared.RabbitMQQueueFormatter:
    class: ../../../../Context/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQQueueFormatter
    arguments: ['PlantsQR']



  Shared.domain.QueryBus:
    class: ../../../../Context/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Shared.domain.QueryHandlers']

  Shared.domain.QueryHandlers:
    class: ../../../../Context/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  Shared.domain.CommandHandlers:
    class: ../../../../Context/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  Shared.domain.CommandBus:
    class: ../../../../Context/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Shared.domain.CommandHandlers']

  Shared.domain.MongoConnector:
    class: ../../../../Context/Shared/infrastructure/Mongo/MongoConnector
    arguments: []

  Shared.domain.MongoRepository:
    class: ../../../../Context/Shared/infrastructure/Mongo/MongoRepository
    arguments: ['@Shared.domain.MongoConnector']
