services:

  Apps.controllers.PlantsGetController:
    class: ../../controllers/PlantsGetController
    arguments: ['@Shared.domain.QueryBus']

  Apps.controllers.PlantsPostController:
    class: ../../controllers/PlantsPostController
    arguments: ['@Shared.domain.CommandBus']


  Apps.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []
