services:
  Plants.PlantCreator:
    class: ../../../../Context/Plants/application/PlantCreator
    arguments: ['@Shared.domain.EventBus']

  Plants.PlantsByCriteriaSearcher:
    class: ../../../../Context/Plants/application/SearchByCriteria/PlantsByCriteriaSearcher
    arguments: []


  Plants.SearchPlantsByCriteriaQueryHandler:
    class: ../../../../Context/Plants/application/SearchByCriteria/SearchPlantsByCriteriaQueryHandler
    arguments: [ '@Plants.PlantsByCriteriaSearcher' ]
    tags:
      - { name: 'queryHandler' }

  Plants.CreatePlantCommandHandler:
    class: ../../../../Context/Plants/application/CreatePlantCommandHandler
    arguments: ['@Plants.PlantCreator']
    tags:
      - { name: 'commandHandler' }

  Plants.PlantCreatedEmailSender:
    class: ../../../../Context/Plants/application/PlantCreatedEmailSender
    arguments: []

  Plants.SendEmailOnPlantCreated:
    class: ../../../../Context/Plants/application/SendEmailOnPlantCreated
    arguments: ['@Plants.PlantCreatedEmailSender']
    tags:
      - { name: 'domainEventSubscriber' }
