services:
  Plants.PlantRepository:
    class: ../../../../Context/Plants/infrastructure/PlantsMongoRepository
    arguments: [ '@Shared.domain.MongoRepository' ]

  Plants.PlantCreator:
    class: ../../../../Context/Plants/application/PlantCreator
    arguments: ['@Shared.domain.EventBus', '@Plants.PlantRepository']

  Plants.PlantDeleter:
    class: ../../../../Context/Plants/application/PlantDeleter
    arguments: ['@Plants.PlantRepository']

  Plants.PlantsByCriteriaSearcher:
    class: ../../../../Context/Plants/application/SearchByCriteria/PlantsByCriteriaSearcher
    arguments: ['@Plants.PlantRepository']

  Plants.PlantByIdSearcher:
    class: ../../../../Context/Plants/application/SearchById/PlantByIdSearcher
    arguments: ['@Plants.PlantRepository']


  Plants.SearchPlantsByCriteriaQueryHandler:
    class: ../../../../Context/Plants/application/SearchByCriteria/SearchPlantsByCriteriaQueryHandler
    arguments: [ '@Plants.PlantsByCriteriaSearcher' ]
    tags:
      - { name: 'queryHandler' }


  Plants.SearchPlantByIdQueryHandler:
    class: ../../../../Context/Plants/application/SearchById/SearchPlantByIdQueryHandler
    arguments: [ '@Plants.PlantByIdSearcher' ]
    tags:
      - { name: 'queryHandler' }

  Plants.CreatePlantCommandHandler:
    class: ../../../../Context/Plants/application/CreatePlantCommandHandler
    arguments: ['@Plants.PlantCreator']
    tags:
      - { name: 'commandHandler' }

  Plants.DeletePlantCommandHandler:
    class: ../../../../Context/Plants/application/DeletePlantCommandHandler
    arguments: ['@Plants.PlantDeleter']
    tags:
      - { name: 'commandHandler' }

  Plants.PlantCreatedEmailSender:
    class: ../../../../Context/Plants/application/PlantCreatedEmailSender
    arguments: []

  Plants.SendEmailOnPlantCreated:
    class: ../../../../Context/Plants/application/SendEmailOnPlantCreated
    arguments: ['@Plants.PlantCreatedEmailSender']
    tags:
      - { name: 'domainEventSubscriber' }
